//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC_601_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Person
    {
        [DisplayName("ID")]
        [Required(ErrorMessage = "This field is required.")]
        public int idNum { get; set; }
        [DisplayName("Nombre")]
        [Required(ErrorMessage = "This field is required.")]
        public string first_name { get; set; }
        [DisplayName("Apellidos")]
        [Required(ErrorMessage = "This field is required.")]
        public string last_name { get; set; }
        [DisplayName("Fecha Registro")]
        [Required(ErrorMessage = "This field is required.")]
        public Nullable<System.DateTime> registerDate { get; set; }
        [DisplayName("Fecha Nacimiento")]
        [Required(ErrorMessage = "This field is required.")]
        public Nullable<System.DateTime> birthDate { get; set; }
        [DisplayName("Teléfono")]
        [Required(ErrorMessage = "This field is required.")]
        public string phone { get; set; }
    
        public virtual UserCred UserCred { get; set; }
    }
}
