//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC_601_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Schedule
    {
        [DisplayName("ID")]
        [Required(ErrorMessage = "This field is required.")]
        public int id { get; set; }
        [DisplayName("Hora")]
        [Required(ErrorMessage = "This field is required.")]
        public string time { get; set; }
        [DisplayName("Duración")]
        [Required(ErrorMessage = "This field is required.")]
        public Nullable<int> duration { get; set; }
        [DisplayName("Capacidad")]
        [Required(ErrorMessage = "This field is required.")]
        public Nullable<int> capacity { get; set; }
    }
}
